### ISSUE TITLE
Modify CI to build and release both with and without the `raspberry` feature

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/espflash#250]
Presently the `raspberry` feature is not enabled in our CI workflow. Since we're unable to test builds for this without actually doing so on a Pi (or messing around with cross-compilation) it'd be best if we could check this automatically.

**Comment by SergioGasquez** [comment]
Hi! After some evaluation I found the following options:
1. Have the package and rust checks into the same file for raspberry targets. 
   - This felt weird as raspberry targets had a single file for `rust` and `package` while the others targets had two.
2. Use a single file for Raspberry targets as in the first option, but merge the current `rust.yml` with the current `package.yml`, so that non-raspberry targets have also a single file.
   - Files become harder to read.
3. Split raspberry stuff into two files: One for rust checks and another for creating release packages, as we do for other targets.
   - It maintains the way files were organized and keeps the files relatively simple. There are still some differences between Raspberry targets and others, for example, rust checks for raspberry targets are executed in a matrix, while for the other targets they are not.
 I went for option 3 in #255, but I am happy to change to any of the other option(it may not be in my list).
