### ISSUE TITLE
espflash monitor without "connecting"?

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/espflash#346]
Example: I have a debugger session running but I want to view UART output. Right now running the monitor subcommand will reset the chip to detect what it is. It will also load the stub, which seems unnecessary for the monitor subcommand.

Perhaps it should be possible to optionally pass the chip via the CLI, if it's passed then espflash won't try and autodetect the chip and instead just go straight to monitoring.

**Comment by jessebraham** [comment]
Looking at the monitor implementation I'm not sure we even need to pass the chip? Seems to be agnostic in that regard, unless I'm missing something.

I agree the stub isn't really necessary for the monitor so that could easily be disabled I'm sure. This shouldn't require too many changes I don't think, I'll look into it soon.
