### ISSUE TITLE
cargo-espflash's `--erase-part` option requires `--partition-table` even when the partition table is set via metadata

### ISSUE THREAD

**Issue by jmesmon** [esp-rs/espflash#390]
When passing `--erase-part` to `cargo-espflash` for a package that has a partition table in package metadata (ie: in `Cargo.toml`'s `[package.metadata.espflash]` section), `cargo-espflash` still complains with:

```
error: the following required arguments were not provided:
  --partition-table <FILE>
```

Instead of returning an error, `cargo-espflash` should use the partition table provided by the metadata when a partition erase is requested (if that metadata is present for the package used).

**Comment by SergioGasquez** [comment]
I've peeked into this issue, and there is some entangling to solve. Both `--erase-parts` and `--erase-data-parts` [require `--partition-table`](https://github.com/esp-rs/espflash/blob/main/espflash/src/cli/mod.rs#L91-L107) since in `espflash` we dont access the `Cargo.toml`, hence we can't read the partition from there. In `cargo-espflash` we reuse the `FlashArgs` defined in `espflash`. 

One possible solution would be to remove the requirement of `--partition-table` and improve the error message when it's not supplied suggesting that you may have missed adding it. 
  - This would mean the error occurs when trying to erase the partitions and not when checking the cli args like right now.
  - Not a really clean approach for the above reasons.
